# Tutorial 1. Make PDF with Numpy

## 1. Basic Data structure in Python
There are 4 basic data structure in Python which you must know them in the first class of Python : ***tuple***, ***list***, ***set*** and ***dict***.

## 1.1. What's is tuple
* Mutable : False
* Index : True
* Duplicate : True
* Multitype : True
* Multidimension : True
* Sizable sub-dimension : True
* Logical operater : False
* Common usage : To store any group of data which are constants.

In [1]:
a = (1, 1, 2.1, 'hello')
print(type(a))
print(a)
print(a[0])
print(a[-1])
print(a[-2])
print(a[1:3])

<class 'tuple'>
(1, 1, 2.1, 'hello')
1
hello
2.1
(1, 2.1)


In [22]:
b = ((1,1), (2,3,'4'), (5))
print(b[1][:])

(2, 3, '4')


### 1.2. What's is list
* Mutable : True
* Index : True
* Duplicate : True
* Multitype : True
* Multidimension : True
* Sizable sub-dimension : True
* Logical operater : False
* Common usage : To store any group of data, and the elements may be replaced or appended.

In [2]:
a = [1, 1, 2.1, 'hello']
print(type(a))
print(a)
print(a[0])
print(a[-1])
print(a[-2])
print(a[1:3])

<class 'list'>
[1, 1, 2.1, 'hello']
1
hello
2.1
[1, 2.1]


In [3]:
a[0] = 2
print(a)
a.append('world')
print(a)

[2, 1, 2.1, 'hello']
[2, 1, 2.1, 'hello', 'world']


In [4]:
# Data structure - Queue (first-in-first-out)
out = a.pop(0)
print(out, a)
# Data structure - Stack (first-in-last-out)
out = a.pop(-1)
print(out, a)

2 [1, 2.1, 'hello', 'world']
world [1, 2.1, 'hello']


In [26]:
b = [[1,1], [2,3,'4'], 5]
print(b[1][:])

[1, 1]


### 1.3. What's is set
* Mutable : True
* Index : False
* Duplicate : False
* Multitype : True
* Multidimension : False
* Sizable sub-dimension : False
* Logical operater : True
* Common usage : To compare the difference of two dataset, i.e. intersection, union or difference

In [5]:
a = {1, 1, 2.1, 'hello', 2}
b = {1, 3, 'hello', 'world'}
print(type(a))
print(a)
print(b)

<class 'set'>
{'hello', 1, 2.1, 2}
{'hello', 1, 3, 'world'}


In [6]:
print("Difference a - b :", a.difference(b))
print("Difference b - a :", b.difference(a))
print("Intersection b & a :", a.intersection(b))
print("Union a | b :", a.union(b))

Difference a - b : {2.1, 2}
Difference b - a : {3, 'world'}
Intersection b & a : {'hello', 1}
Union a | b : {1, 2.1, 2, 3, 'hello', 'world'}


### 1.4. What's is dict
* Mutable : True
* Index : False
* Duplicate : False
* Multitype : True
* Multidimension : True
* Sizable sub-dimension : True
* Logical operater : False
* Common usage : The hashmap data structure base. The indexing is made with keys.

In [7]:
a = {1:2, 'b':3, 2:'a'}
print(a)
print('keys : ', a.keys())
print('values : ', a.values())

{1: 2, 'b': 3, 2: 'a'}
keys :  dict_keys([1, 'b', 2])
values :  dict_values([2, 3, 'a'])


In [8]:
a['c'] = 'd'
a[1] = 3
print(a)

{1: 3, 'b': 3, 2: 'a', 'c': 'd'}


In [27]:
b = {'hello':{1:'world', 2:'kitty'}, 3:4}
print(b['hello'][2])

kitty


### 1.5. Change type

In [9]:
a = (1, 1, 2.1, 'hello')
print(list(a))
print(set(a))

[1, 1, 2.1, 'hello']
{'hello', 1, 2.1}


## 2. The advance data structure in Python (Numpy.array)
Numpy is the extra python package for numarical computation.
* Mutable : True
* Index : True
* Duplicate : True
* Multitype : False
* Multidimension : True
* Sizable sub-dimension : False
* Logical operater : True

In [10]:
import numpy as NP

In [32]:
a = NP.array([1, 2, 3, 4])
b = NP.array([1., 2., 3., 4.])
print(a, type(a), a.dtype)
print(b, type(b), b.dtype)

[1 2 3 4] <class 'numpy.ndarray'> int64
[1. 2. 3. 4.] <class 'numpy.ndarray'> float64


In [16]:
# logic
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)
print(a > b)
print(a < b)
print(a == b)
print(a != b)

[2. 4. 6. 8.]
[0. 0. 0. 0.]
[ 1.  4.  9. 16.]
[1. 1. 1. 1.]
[0. 0. 0. 0.]
[False False False False]
[False False False False]
[ True  True  True  True]
[False False False False]
[1.41421356 2.82842712 4.24264069 5.65685425]


In [17]:
# math
print(NP.mean(a), NP.mean(b))
print(NP.std(a), NP.std(b))
print(NP.sqrt(a**2 + b**2))

2.5 2.5
1.118033988749895 1.118033988749895
[1.41421356 2.82842712 4.24264069 5.65685425]


In [38]:
# selection
msk = a < 3
print(a)
print(msk) 
print(a[msk])
print(a[a < 3])

[1 2 3 4]
[ True  True False False]
[1 2]
[1 2]


In [47]:
# 2D
b = NP.array([[0, 1,2], [3,4,5], [6,7,8]])
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [49]:
# math
print(NP.transpose(b))
print(NP.tril(b))
print(NP.triu(b))
print(NP.invert(b))

[[0 3 6]
 [1 4 7]
 [2 5 8]]
[[0 0 0]
 [3 4 0]
 [6 7 8]]
[[0 1 2]
 [0 4 5]
 [0 0 8]]
[[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]


In [52]:
c = NP.array([1,0,-1])
print(b.dot(c))

[-2 -2 -2]
